### ISSUE TITLE
Manually triggering an animation

### ISSUE THREAD

**Issue by gathrlabs** [BenAHammond/vue-anime#4]
Great plugin! Super helpful for easily accessing animejs.

What would be your recommendation for manually triggering animations?

**Comment by BenAHammond** [comment]
Thanks! I appreciate the feedback.

`this.$anime` is available inside your components so you can do something like:

```
export default {
  name: "my-component",
  data() {
    return {};
  },
  mounted() {
    this.$anime(/* ... animate something ... */)
  },
}
```

**Comment by gathrlabs** [comment]
I noticed that snippet but then was unsure how to target elements. I just had to look through the anime docs to remind myself how to use the targets property. Might be worth throwing an example into your docs to demonstrate the "animate something" part.

```
export default {
  name: "my-component",
  data() {
    return {};
  },
  mounted() {
    this.$anime({
        targets: 'div', 
        translateX: 250,
        scale: 2,
        rotate: '1turn' 
     })
  },
}
```
Just a thought, thanks again! I'll close this issue now.

**Comment by BenAHammond** [comment]
Good feedback, I will patch that in when I get some time.
